import dotenv from 'dotenv'
import connectDB from '../config/db.js'
import Product from '../models/Product.js'

dotenv.config()

const products = [
  {
    name: 'Canon Camera EOS 2000, Black 10x zoom',
    category: 'Consumer electronics',
    price: 998,
    oldPrice: 1128,
    rating: 4.8,
    reviews: 154,
    sold: 500,
    stock: 24,
    featured: true,
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    description: 'Professional digital camera with sharp image quality, fast autofocus, and durable body for travel or studio work.',
    supplier: 'Guanjoi Trading LLC',
    location: 'Germany, Berlin',
    specs: { Model: 'EOS 2000', Style: 'DSLR camera', Material: 'Aluminum body', Warranty: '2 years' },
  },
  {
    name: 'GoPro HERO6 4K Action Camera',
    category: 'Consumer electronics',
    price: 799,
    oldPrice: 920,
    rating: 4.7,
    reviews: 98,
    sold: 320,
    stock: 18,
    featured: true,
    image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=800&q=80',
    description: 'Compact action camera for outdoor filming, waterproof trips, and high-resolution video capture.',
    supplier: 'SourceNow GmbH',
    location: 'China, Shenzhen',
    specs: { Resolution: '4K', Battery: '2 hours', Connectivity: 'WiFi, Bluetooth', Warranty: '1 year' },
  },
  {
    name: 'Apple Watch Series with sport band',
    category: 'Computer and tech',
    price: 399,
    oldPrice: 449,
    rating: 4.9,
    reviews: 231,
    sold: 810,
    stock: 42,
    featured: true,
    image: 'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?auto=format&fit=crop&w=800&q=80',
    description: 'Smart wearable with activity tracking, notifications, heart-rate insights, and everyday style.',
    supplier: 'BlueMarket Supply',
    location: 'United States',
    specs: { Display: 'Retina', Band: 'Sport silicone', Battery: '18 hours', Warranty: '1 year' },
  },
  {
    name: 'Modern wireless headphones',
    category: 'Consumer electronics',
    price: 129,
    oldPrice: 169,
    rating: 4.6,
    reviews: 76,
    sold: 245,
    stock: 67,
    featured: false,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    description: 'Comfortable headphones with balanced sound, soft ear cushions, and long battery life.',
    supplier: 'AudioPro Export',
    location: 'Japan, Tokyo',
    verified: false,
    specs: { Type: 'Over-ear', Battery: '32 hours', NoiseCanceling: 'Active', Warranty: '1 year' },
  },
  {
    name: 'Blue cotton mens casual jacket',
    category: 'Clothes and wear',
    price: 49,
    oldPrice: 69,
    rating: 4.4,
    reviews: 63,
    sold: 190,
    stock: 90,
    featured: true,
    image: 'https://images.unsplash.com/photo-1520975954732-35dd22299614?auto=format&fit=crop&w=800&q=80',
    description: 'Soft cotton jacket with practical pockets and a clean fit for daily casual wear.',
    supplier: 'Fashion Bridge',
    location: 'Italy, Milan',
    specs: { Material: 'Cotton', Gender: 'Men', Season: 'Spring', Fit: 'Regular' },
  },
  {
    name: 'Ergonomic office chair with mesh back',
    category: 'Home interiors',
    price: 189,
    oldPrice: 240,
    rating: 4.5,
    reviews: 87,
    sold: 140,
    shipping: 'Paid Shipping',
    stock: 31,
    featured: false,
    image: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?auto=format&fit=crop&w=800&q=80',
    description: 'Adjustable chair with breathable mesh, lumbar support, and smooth rolling base.',
    supplier: 'HomePro Wholesale',
    location: 'Denmark',
    specs: { Material: 'Mesh and steel', Color: 'Black', Adjustable: 'Yes', Warranty: '3 years' },
  },
  {
    name: 'Kitchen blender stainless steel set',
    category: 'Home interiors',
    price: 75,
    oldPrice: 95,
    rating: 4.3,
    reviews: 52,
    sold: 105,
    stock: 46,
    featured: false,
    image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=800&q=80',
    description: 'Durable kitchen blender for smoothies, sauces, and quick home meal preparation.',
    supplier: 'KitchenTrade Co.',
    location: 'France',
    verified: false,
    specs: { Power: '600W', Jar: '1.5L', Material: 'Steel', Warranty: '1 year' },
  },
  {
    name: 'Cordless drill professional tool kit',
    category: 'Tools, equipments',
    price: 145,
    oldPrice: 188,
    rating: 4.7,
    reviews: 118,
    sold: 430,
    stock: 28,
    featured: true,
    image: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&w=800&q=80',
    description: 'Powerful cordless drill kit with battery pack, bit set, and hard carry case.',
    supplier: 'BuildTools Direct',
    location: 'United States',
    specs: { Voltage: '20V', Battery: 'Lithium', Pieces: '32', Warranty: '2 years' },
  },
  {
    name: 'Smartphone with large display 128GB',
    category: 'Computer and tech',
    price: 299,
    oldPrice: 359,
    rating: 4.5,
    reviews: 184,
    sold: 620,
    stock: 53,
    featured: true,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
    description: 'Reliable smartphone with large display, fast processor, and generous storage for work and entertainment.',
    supplier: 'MobileHub Export',
    location: 'China, Shenzhen',
    specs: { Storage: '128GB', Display: '6.5 inch', Camera: '48MP', Warranty: '1 year' },
  },
  {
    name: 'Outdoor backpack travel waterproof',
    category: 'Sports and outdoor',
    price: 39,
    oldPrice: 54,
    rating: 4.2,
    reviews: 47,
    sold: 94,
    stock: 120,
    featured: false,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    description: 'Lightweight travel backpack with water-resistant fabric and organized storage compartments.',
    supplier: 'Outdoor Base',
    location: 'Australia',
    specs: { Capacity: '28L', Material: 'Polyester', Waterproof: 'Yes', Warranty: '1 year' },
  },
]

async function seedProducts() {
  await connectDB()
  await Product.deleteMany()
  await Product.insertMany(products)
  console.log(`${products.length} products inserted`)
  process.exit()
}

seedProducts().catch((error) => {
  console.error(error)
  process.exit(1)
})
